import Services from './service'

//#region Identity
// Services.Identity.validateMnemonic
Services.Identity.queryProfile
Services.Identity.queryProfilePaged
Services.Identity.queryProfiles
Services.Identity.queryProfilesWithIdentifiers
Services.Identity.queryMyProfiles
Services.Identity.updateProfileInfo
Services.Identity.removeProfile
Services.Identity.attachProfile
Services.Identity.detachProfile

Services.Identity.queryPersona
Services.Identity.createPersonaByMnemonic
Services.Identity.createPersonaByMnemonicV2
Services.Identity.renamePersona
Services.Identity.queryPersonaByMnemonic
Services.Identity.queryPersonas
Services.Identity.queryMyPersonas
Services.Identity.queryLastPersonaCreated
Services.Identity.queryPrivateKey
Services.Identity.backupPersonaPrivateKey
Services.Identity.queryOwnedPersonaInformation
Services.Identity.setupPersona
Services.Identity.deletePersona
Services.Identity.logoutPersona
Services.Identity.exportPersonaPrivateKey
Services.Identity.createPersonaByPrivateKey
Services.Identity.queryPersonaByPrivateKey

Services.Identity.restoreFromObject
Services.Identity.restoreFromMnemonicWords
Services.Identity.restoreFromBase64
Services.Identity.restoreFromBackup

Services.Identity.queryPostsDB
Services.Identity.queryPagedPostHistory
Services.Identity.signWithPersona

Services.Identity.patchCreateOrUpdateRelation
Services.Identity.patchCreateNewRelation
Services.Identity.createNewRelation
Services.Identity.queryRelationPaged
Services.Identity.updateRelation

Services.Identity.resolveIdentity

Services.Identity.updateCurrentPersonaAvatar
Services.Identity.getCurrentPersonaAvatar
//#endregion

Services.Crypto.verifyOthersProve

//#region Welcome
Services.Welcome.generateBackupJSON
Services.Welcome.generateBackupPreviewInfo
Services.Welcome.confirmBackup
Services.Welcome.getUnconfirmedBackup
Services.Welcome.restoreBackup
Services.Welcome.setUnconfirmedBackup
Services.Welcome.restoreNewIdentityWithMnemonicWord
Services.Welcome.downloadBackup
Services.Welcome.downloadBackupV2
Services.Welcome.createBackupFile
Services.Welcome.createBackupUrl
Services.Welcome.openOptionsPage
Services.Welcome.createPersonaByMnemonic
Services.Welcome.parseBackupStr
Services.Welcome.checkPermissionsAndRestore
//#endregion
